framework:
#    messenger:
#        failure_transport: failed
#
#        transports:
#            # https://symfony.com/doc/current/messenger.html#transport-configuration
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    use_notify: true
#                    check_delayed_interval: 60000
#                retry_strategy:
#                    max_retries: 3
#                    delay: 1000
#                    multiplier: 2
#                    max_delay: 0
#            failed: 'doctrine://default?queue_name=failed'
#            # sync: 'sync://'
#
#        default_bus: messenger.bus.default
#
#        buses:
#            messenger.bus.default: []
#
#        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#
#            # Route your messages to the transports
#            # 'App\Message\YourMessage': async
