controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\DashboardController::index


dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    name_prefix: admin_sih_dashboard


signin:
    path: /signin
    controller: App\Controller\Auth\AuthController::signin


#signup:
#    path: /signup
#    controller: App\Controller\Auth\RegisterController::signup


reset-password:
    path: /reset-password
    controller: App\Controller\Auth\AuthController::reset_password


new-password:
    path: /new-password
    controller: App\Controller\AuthController::new_password